baseURL = "https://discoverfoss.com/"
languageCode = "en-us"
copyright = "This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License."
title = "Discover FOSS"
theme = "notepadium"
publishDir = "/home/mowest/gitprojects/mowestusa.github.io/"
enableRobotsTXT = true

[author]
name = "Steve (mowest)"

[markup.highlight]
codeFences = true
noClasses = false

[params]
style = "dark"
logo = "/img/discover-100px.png"
slogan = "Discover Free and Open Source Software"

[params.syntax]
use = "none"
theme = "xcode"
darkTheme = "xcode-dark"

[params.nav]
showCategories = true
showTags = true

[[params.nav.custom]]
title = "RSS"
url = "/index.xml"

# [params.nav.custom]
# title = "About"
# url = "/about"

[params.profile]
    enable = true
    avatar = "/img/myAvatar.png"
    name = "Steve (mowest)"
    bio = "A free and open source enthusiast using these tools for work and fun."
    github = "mowestusa"
    email = "mowestusa@pm.me"
